### ISSUE TITLE
`useModule` does not properly check that caller is a SecurityToken

### ISSUE THREAD

**Issue by adamdossa** [PolymathNetwork/polymath-core#106]
`useModule` calls `getSecurityTokenData` in the SecurityTokenRegistrar, which in turn checks the owner of the referenced security token address. However, this call will succeed provided the referenced security token address has an `owner` variable, even if the address is not actually a security token.

A better option would be to check that the address is in the STR registry, but this is not possible for modules deployed via the STVersionProxy*.sol contracts as they add modules before the token has been added to the STR registry.

**Comment by pabloruiz55** [comment]
What problems/vulnerabilities does this pose?

**Comment by adamdossa** [comment]
It allows a malicious actor to spuriously modify the reputation of a module in the registry by registering lots of use, outside of the intended ST usage.

A simple fix would be to only register usage for registered security tokens, although this will mean that use of the GTM is not registered (as this is added before the ST is registered in the STR). Since we don't really care about the reputation of this module (since it is a core Polymath module) this is probably fine.

**Comment by pabloruiz55** [comment]
Got it. Let's add this to the backlog for next sprint.
