### ISSUE TITLE
Module Upgrading

### ISSUE THREAD

**Issue by pabloruiz55** [PolymathNetwork/polymath-core#207]
Do we need something beyond what we already have? What is the downside to this approach:
  - deploy new CappedSTOFactory contract with updated logic.
  - un-verify the previous CappedSTOFactory contract in the module registry
  - verify the new CappedSTOFactory in the module registry
  - in the dApp change over to the new CappedSTOFactory address
At this point, the only CappedSTO that users will be able to add to their token is the new version (they can't add the old version as it was deployed by Polymath, so address won't match issuer address).
Any existing tokens w/ capped STOs attached should not be affected.
Module names are not unique (someone else could register a CappedSTOFactory with the same tags & names in the module registry), only their addresses are, so I don't think it is a problem having two CappedSTOs in the module registry, provided only one of them is verified.
We should add an additional function in the module registry to allow module owners to remove their modules from the registry if they wish to, but we don't need to rely on this happening.
NB - if we change the way we manage modules as per @Stephane meeting then this may need to be reviewed.

----
Questions: 
  - Is it reasonable to "not allow" modules to have any dependencies on the STR? There may be use-cases where this it is useful for a module to have a view of the overall security token registries (e.g. to look up other tokens owned by the same issuer).
  - We could have a "DataFeed" module type of which the oracles would be one example of. This would allow us to charge for data feeds if we wanted to. We would need to decide whether every e.g. POLYUSD data feed used the same source (i.e. as it works today) or whether everyone get's their own oracle that they need to maintain (I'm not a fan of this).

**Comment by adamdossa** [comment]
Modules should have a dependency on the security token version (since there are dependencies between the module and the security token it is attached to).

**Comment by adamdossa** [comment]
Addressed in dev-3.0.0
