### ISSUE TITLE
Security Token Upgrading

### ISSUE THREAD

**Issue by pabloruiz55** [PolymathNetwork/polymath-core#208]
- I don't think we should be looking to facilitate upgrading in place for security tokens for a host of reasons (gives issuers too much power / ability to screw up).
  - It would however be quite nice to allow an issuer to create a new token as a clone from a previous one, which should be possible given the checkpoint functionality. This means that if an issuer wants to upgrade to a later version of the security token they can do, carrying over existing balances (similar to the clone behaviour of MiniMe). This would need some thought as to the exact mechanics of how this would work.

**Comment by adamdossa** [comment]
Addressed in dev-3.0.0
