### ISSUE TITLE
Unnecessary looping when FORCE_VALID returns

### ISSUE THREAD

**Issue by darioAnongba** [PolymathNetwork/polymath-core#273]
Hi,

I was looking at the Polymath code and realized something that is not optimised in the `SecurityToken.sol` file. So just letting you know. I might be wrong on this. This piece of code:

```solidity
bool isInvalid = false;
bool isValid = false;
bool isForceValid = false;
for (uint8 i = 0; i < modules[TRANSFERMANAGER_KEY].length; i++) {
    ITransferManager.Result valid = ITransferManager(modules[TRANSFERMANAGER_KEY][i].moduleAddress).verifyTransfer(_from, _to, _amount, isTransfer);
    if (valid == ITransferManager.Result.INVALID) {
         isInvalid = true;
    }
    if (valid == ITransferManager.Result.VALID) {
        isValid = true;
    }
    if (valid == ITransferManager.Result.FORCE_VALID) {
        isForceValid = true;
    }
}
return isForceValid ? true : (isInvalid ? false : isValid);
```

could be:

```solidity
bool isInvalid = false;
bool isValid = false;
for (uint8 i = 0; i < modules[TRANSFERMANAGER_KEY].length; i++) {
    ITransferManager.Result valid = ITransferManager(modules[TRANSFERMANAGER_KEY][i].moduleAddress).verifyTransfer(_from, _to, _amount, isTransfer);
    if (valid == ITransferManager.Result.INVALID) {
         isInvalid = true;
    }
    if (valid == ITransferManager.Result.VALID) {
        isValid = true;
    }
    if (valid == ITransferManager.Result.FORCE_VALID) {
        return true;
    }
}
return isInvalid ? false : isValid;
```
So as soon as you hit a FORCE_VALID you automatically return `true` instead of going through all other TransferManagers.

**Comment by adamdossa** [comment]
Hi @darioAnongba - firstly - thanks for the feedback and reviewing the code.

Looking at the code I think you're correct - we can always return true if we receive a FORCE_VALID from a TransferManager - thanks for spotting this!

**Comment by darioAnongba** [comment]
Also, by checking the order of the if statements and doing first the FORCE_VALID, then the INVALID and finally the VALID and using `if - else if` will also improve the code, because a `Result` can only be one of those.

```solidity
if (valid == ITransferManager.Result.FORCE_VALID) {
    return true;
}
else if (valid == ITransferManager.Result.INVALID) {    
    isInvalid = true;
}
else if (valid == ITransferManager.Result.VALID) {
    isValid = true;
}
```

Although this should be optimised at compilation time.

**Comment by adamdossa** [comment]
Going to leave this open until we fix it.

**Comment by adamdossa** [comment]
I just reviewed this and we can't make this optimisation.

We need to ensure that all transfer managers "see" all transfers that happen, in case they have internal state they are maintaining related to this.

So we can't short circuit this loop unfortunately.
