### ISSUE TITLE
Add getCurrentMaxAllowTransfer to ITransferManager

### ISSUE THREAD

**Issue by tanpv** [PolymathNetwork/polymath-core#346]
### Problem
- ITransferManager lack of function which return max amount of token which allow
transfer from one investor to other investor at a specific moment of time

- Use this function investor could transfer easily without need to guess
how much they could transfer at current time 

### Solution
- Define function _getCurrentMaxAllowTransfer_ in side _ITransferManager_
- Each transfer manager module will implement it self the function _getCurrentMaxAllowTransfer_. Because each Transfer Manager module has it own rule or way of distribute token over time.
- When transfer is INVALID, _getCurrentMaxAllowTransfer_ simply return 0

**Comment by adamdossa** [comment]
Hi @tanpv - thanks for the suggestion. We are aiming to tackle this using ERC-1410 to record the amount of unlocked tokens. This is scheduled tentatively for version 3.0 of the protocol.
