### ISSUE TITLE
Transfer and Approve event naming inconsistencies

### ISSUE THREAD

**Issue by monitz87** [PolymathNetwork/polymath-core#412]
I found an inconsistency in the naming of the `Transfer` and `Approval` event parameters between `PolyToken` and `PolyTokenFaucet`. In `PolyTokenFaucet` all parameters are prefaced by an underscore (i.e. `_from`, `_to`, `_value`), while in `PolyToken` they are not. This causes inconsistent behavior when switching between mainnet and kovan in the dApp.

I suggest renaming the PolyToken event parameters to include underscores as defined by ERC20

**Comment by maxsam4** [comment]
Can't change `PolyToken` as it's live on mainnet. I'll refactor `PolyTokenFaucet`.

**Comment by monitz87** [comment]
I understand, wasn't really thinking when I suggested it haha

**Comment by maxsam4** [comment]
ERC20 standard defines the event parameter names with underscores. 

Refactoring of `PolyTokenFaucet` depends on what OpenZeppelin decides to do
https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1175

**Comment by maxsam4** [comment]
Fixed in https://github.com/PolymathNetwork/polymath-core/pull/480
