### ISSUE TITLE
SecurityToken:addModule "Module exists" exception will never happen!!!

### ISSUE THREAD

**Issue by steventranjs** [PolymathNetwork/polymath-core#418]
**Suspected Problem**
Below lines are inside `SecurityToken:addModule` function:
```
address module = moduleFactory.deploy(_data);
require(modulesToData[module].module == address(0), "Module exists");
```
- As `moduleFactory.deploy(_data)` always return a new contract address which is subsequently added as new key of `modulesToData`. Therefore, the `require` checking condition will never meet. 
- This will results duplicated added modules if this function  `SecurityToken:addModule` is accidentally called twice or more.
- Duplicate added modules will cause unnecessary gas cost for execution. 
- If duplicated modules were accepted, then should remove `require` condition.

**Solution**
- Use `_moduleFactory` instead of `module` as `modulesToData`'s key to make sure unique `_moduleFactory` should be added at once. This means only 1 module instance is deployed from the factory.
- If this problem is acknowledged, I would like to make a PR for this.

**Comment by adamdossa** [comment]
Hey @steventranjs - thanks very much for taking a look at this code - interesting observation!

Our current thinking is that `moduleFactory.deploy(_data)` may not always return a newly generated contract address each time it is called. For example there may be a module where the associated factory is a "singleton factory" - i.e. the underlying module contract is shared across multiple tokens that attach it (this could be a whitelist contract that is shared across multiple tokens).

In this case, the `require` statement would check that the current module has not already been attached (a true duplicate in the sense that the underlying module address had been attached twice). In general there will be some cases where the same type of module is added twice to a token (for example adding two vesting modules, one used for one group of investors, and the other for a different group of investors). In this second case the underlying module address would be different, so the `require` statement wouldn't be triggered.

Does this make sense? To summarise we want to restrict that all modules have unique addresses for a given token, but allow `addModule` to be called for the same moduleFactory multiple times (provided that module factory generates new underlying module contracts each time).

**Comment by steventranjs** [comment]
Thanks @adamdossa for your explanation, appreciate your points of singleton factory & duplicate modules for diff investors. This all make sense to me. 

In addition, I think it will be good if we can have a `SecurityTokenExample` with non-duplicated `_moduleFactory` feature as I mentioned above. This will help in some use cases. 

For example, I can deploy new `ModuleFactory` address (of the same existing ModuleFactory code) and add it as new module. By doing this way I can both maintain the uniqueness of `_moduleFactory ` address & support duplicate features for diff investors. 

I would like to make the example contract if possible.

Best regards

**Comment by adamdossa** [comment]
Hi @steventranjs - we are refactoring our module factories in the next major release to allow in-place upgrades of underlying module code. I think it is easier, when adding multiple instances of the same factory, to simply recall the deploy function of the module factory rather than having to redeploy a new factory (which could effect all security tokens).
