### ISSUE TITLE
Eternal storage redundant functions

### ISSUE THREAD

**Issue by maxsam4** [PolymathNetwork/polymath-core#483]
There are a few redundant functions in the [eternal storage contract](https://github.com/PolymathNetwork/polymath-core/blob/master/contracts/storage/EternalStorage.sol)
like
```
function getBool(bytes32 _key) internal view returns (bool) {
        return boolStorage[_key];
}
```
and
```
function getBoolValues(bytes32 _variable) public view returns(bool) {
        return boolStorage[_variable];
}
```
The internal functions can be removed and code can be refactored to use the public function instead.

**Comment by dev1644** [comment]
I am working on it.

**Comment by maxsam4** [comment]
Closed by https://github.com/PolymathNetwork/polymath-core/pull/488
Thank you @dev1644 for your contribution
