### ISSUE TITLE
Eternal Storage missing public functions

### ISSUE THREAD

**Issue by maxsam4** [PolymathNetwork/polymath-core#484]
In the [eternal storage contract](https://github.com/PolymathNetwork/polymath-core/blob/master/contracts/storage/EternalStorage.sol), There are public functions for getting Elementary Data Type variables like uint but the functions to get Arrays are marked internal. Those functions can also be useful to outside world and should be marked public.

functions like
```
function getArrayAddress(bytes32 _key) internal view returns(address[]) {
        return addressArrayStorage[_key];
}
``` 
should become
```
function getArrayAddress(bytes32 _key) public view returns(address[]) {
        return addressArrayStorage[_key];
}
```

**Comment by dev1644** [comment]
I am working on it.

**Comment by maxsam4** [comment]
Closed by https://github.com/PolymathNetwork/polymath-core/pull/488
Thank you @dev1644 for your contribution.
