### ISSUE TITLE
USDTieredSTO minToken check is after tokens are already minted

### ISSUE THREAD

**Issue by F-OBrien** [PolymathNetwork/polymath-core#497]
I could be very wrong on this but wanted to highlight a potential issue in the USDTieredSTO.sol in Dev 2.1.0 branch.

In both the buyWithETHRateLimited and _buyWithTokens functions the check that the minimum number of tokens has been minted occurs after the _buyTokens function. As tokens are already minted  it is possible for tokens to be issued to the investor and the transaction to revert.
(current logic _buytokens >> _calculateTier >> _purchaseTier >> mint >> return to buyWithETHRateLimited or _buyWithTokens >> check _minTokens)

Instead of minting within the _calculateTier function, as each lot of tokens is calculated, it would be better to only calculate the number of tokens that will be minted and when the total number of tokens is calculated check that against the _minTokens before minting.  This could possibly be done using the _calculateTierView function or similar.

**Comment by adamdossa** [comment]
Hey @F-OBrien - firstly thanks for reviewing the code - it's always great to have active members of the community looking at the code in detail!

I may have mis-understood the concern, but when a transaction reverts (i.e. in the line:
`require(getTokensMinted().sub(initialMinted) >= _minTokens, "Insufficient tokens minted");`
all of the effects of the transaction are reverted.

So in this case, if the number of tokens minted (inside `_buyTokens`) is less than `_minTokens`, the whole transaction would be reverted, including the actual minting of tokens (i.e. it is as if the transaction never happened at all, including the minting of tokens).

Let me know if I mis-understood the concern - thanks!

**Comment by F-OBrien** [comment]
Ah cool that explains that one. I'm not a dev so just learning and as I was reading I thought the order of the check relative to the minting may have mattered but looks like it doesn't.
