### ISSUE TITLE
ST-20 Live website page broken

### ISSUE THREAD

**Issue by abdulwahidgul24085** [PolymathNetwork/polymath-core#506]
Hello, I was reading your website and end up on the ST-20 page. https://polymath.network/resources/st20.html 

 This page is completely broken. I have attached a picture of the view from my computer for reference.  

![polymath error](https://user-images.githubusercontent.com/6042059/50684950-33380380-1039-11e9-9d20-2eea48c73660.png)

**Comment by maxsam4** [comment]
@abdulwahidgul24085 Thanks for reporting this issue!
The updated link is https://polymath.network/st20.html

We have also fixed our 404 responses to look better.
