### ISSUE TITLE
Rename Mint and Burn events to match OpenZeppelin

### ISSUE THREAD

**Issue by wjmelements** [PolymathNetwork/polymath-core#565]
The [OpenZeppelin](https://docs.openzeppelin.org/docs/token_erc20_mintabletoken) token uses events called `Mint` and `Burn`, analogous to your `Minted` and `Burnt`. The scheme is also used by TrueUSD. Adopting their naming scheme would facilitate compatibility.

**Comment by wjmelements** [comment]
### Uses Burn and Mint

OpenZeppelin:
https://docs.openzeppelin.org/docs/token_erc20_burnabletoken
https://docs.openzeppelin.org/docs/token_erc20_mintabletoken

TrustToken (TUSD):
https://github.com/trusttoken/trueUSD/blob/master/contracts/modularERC20/ModularBurnableToken.sol

Centre (USDC):
https://github.com/centrehq/centre-tokens/blob/master/contracts/FiatTokenV1.sol


### Others

As a counterexample, PAX uses `SupplyIncreased` and `SupplyDecreased`.
https://github.com/paxosglobal/pax-contracts/blob/master/contracts/PAXImplementation.sol

**Comment by maxsam4** [comment]
@wjmelements Thanks for looking into our codebase! 

In our latest dev branch (dev-3.0.0) we have decided to use event names set in [IERC1400](https://github.com/ethereum/EIPs/issues/1400) family. More specifically, `Minted` is now `Issued` and `Burned` is now `Redeemed`. These are part of [IERC1594](https://github.com/ethereum/EIPs/issues/1594) and we believe that they represent the Security token use case better.

**Comment by wjmelements** [comment]
Thanks for your reply. If EIP1594 goes through, we may consider upgrading our events to match. Thanks for caring about open standards!
