### ISSUE TITLE
Store and use factory addresses from module registry without depending on name

### ISSUE THREAD

**Issue by VictorVicente** [PolymathNetwork/polymath-core#586]
See https://github.com/PolymathNetwork/polymath-core/pull/585

It is fixed for dividends modules, but it should be fixed too for the others.

**Comment by dev1644** [comment]
Hi @VictorVicente , does this issue still require some work?

**Comment by VictorVicente** [comment]
Sorry @dev1644, it's already solved 👍 
Thank you!
