### ISSUE TITLE
Need Documentation

### ISSUE THREAD

**Issue by blockchain-app12** [PolymathNetwork/polymath-core#648]
Is there any documents to play around given multiple contracts? Its hard to find usage of every single contract.

**Comment by maxsam4** [comment]
There is some documentation available on the GitHub wiki https://github.com/PolymathNetwork/polymath-core/wiki

We are working on adding more.

**Comment by blockchain-app12** [comment]
I wish to know which country's regulation is polymath following  to launch a security token?

**Comment by adamdossa** [comment]
The ST20 framework is modular and intended to be flexible enough to be able to be used across many different jurisdictions. We have a range of compliance modules available (TransferManagers) - is there something which you think is needed for your jurisdiction which is not currently available?

**Comment by satyamakgec** [comment]
No more requirement comes up from the author, Closing this issue
