### ISSUE TITLE
Extend CLI to be middleware server and create web ui layer

### ISSUE THREAD

**Issue by joequant** [PolymathNetwork/polymath-core#653]
## Issue Template

Please use this template when submitting issues to this repo

### Is your feature request related to a problem? Please describe.

The CLI interface is a very nice interface to polymath features, and it can be
extended to create an integration layer for financial institution systems, or to
generate an open source UI system.

Most financial institutions have existing legacy systems that need to interface
with data sources and actions.  The cli layer provides a nice interface for this
and would require the generation of web services.

### Describe the solution you'd like

1) Turn the CLI into a rest-api web service running in a docker container
2) document 
3) design the interface so to create an abstraction so that the users do not see 
underlying implementation details

### Describe alternatives you've considered

Most blockchain projects are poorly abstracted, and have highly coupled systems
which are unsuitable for enterprise computing.

No other proposed token technology has even considered middleware issues.  I will
have to program this layer for my client anyway.  Would be interested in discussion
of alternatives.  Also would be interested in finding open source implementations of
middleware for competing token technologies which can be used as models or whose
code can be integrated.

### Possible Implementation

Just take the current CLI interface and define a rest API that connects with the system

### Additional context

The big issue for financial institutions is going to be cybersecurity as this creates another
attack vector.  However, the issues involved here are typical of web services.  The standard
solution is to put a firewall around corporate systems, and use internal web access controls
to limit access to sensitive functions.

**Comment by VictorVicente** [comment]
This is a great idea we have already discussed it and maybe we could implement in the future. Meanwhile we are developing the necessary tools to make it happen.
Current CLI needs a lot of work to support any change on our contracts. To solve this we split the work in different levels. 
The first layer are our contracts, or the JSON output when they are compiled. We create a new repo containing them to manage our releases for these type of implementations. You can find them here: https://github.com/PolymathNetwork/polymath-contract-artifacts

The second layer takes those artifacts and convert them into typescript classes using automated code generation scripts. This allow us to work much more ordered than the current CLI. https://github.com/PolymathNetwork/polymath-abi-wrappers

Currently, we are working on the third layer. We are making an API to interact with our contracts without the needs to know much about their code. We have standardized input and output types, check for any requirement from the contract to avoid reverts and get clear error messages, etc.
We are working hard on the unit test to make sure all is working fine and as we expect. 
https://github.com/PolymathNetwork/polymath-contract-wrappers

With this API, CLI will be much simpler and easy to read and it will be easier to port to a rest API or a self executable dApp.

There is a lot of things to do, but we are working hard to get them done.
