### ISSUE TITLE
CLI system does not work with docker container networks

### ISSUE THREAD

**Issue by joequant** [PolymathNetwork/polymath-core#654]
I've created a set of docker images on joequant/sto.  Right now the CLI can connect either to a remote node or a ganache-cli running on localhost.  However, docker networking puts the ganache-cli server on a separate container which is accessed by a name which does not have the naming format for remote nodes.

For example, if I start up ganache-cli on a docker image, I need to connect to the node at http://ganache-cli:8545/, the current argument system either forces me to connect to a remote node or localhost.

Getting this to work would involve some changes the cli validation code, and cli interface.

The easy fix would be to add an argument --localNode

Also some more error messages might be useful.  Right now the cli just says that it has a bad response to RPC

**Comment by satyamakgec** [comment]
@joequant  Thanks, It is a useful improvement. If you want to add this feature then please create a PR otherwise we will add this on CLI backlog.

**Comment by joequant** [comment]
Sure.  Working on it.  Right now I'm trying to get the CLI to work with
docker images.  Running into a lot of interface issues, but will send
in pull requests as I get through them.  The work flow right now is, run
the CLI get an error.  Figure out what is causing the error, and
repeat until I get it working.

**Comment by satyamakgec** [comment]
Please try to take a code of `dev-2.1.0` branch because in `dev-3.0.0` CLI is not in sync with the smart contract changes.

**Comment by VictorVicente** [comment]
Hey @joequant, does your PR (https://github.com/PolymathNetwork/polymath-core/pull/669) solve this issue? It has been merged into master.
BTW, error handling is one of the biggest pending tasks on the CLI. We will work on it in the near future to show more accurate messages to the user.
