### ISSUE TITLE
polymath cli triggers ganache-cli bug in 6.4.3 causing crash  in ganache

### ISSUE THREAD

**Issue by joequant** [PolymathNetwork/polymath-core#660]
Creating an ST20 token 2.2.0 CLI and with ganache 6.4.3 backend causes the ganache backend to crash with this bug

https://github.com/trufflesuite/ganache-core/issues/417

Downgrading to 6.2.5 will work.  It might be a good idea to check the version of ganache and then return an warning.

**Comment by maxsam4** [comment]
@joequant We can not guarantee compatibility with each and every version of every dependency. Sometimes other dependencies have some bugs, sometimes they change their APIs. Please use the versions locked in `yarn.lock`.

If you run `yarn install`, yarn will automatically install the proper dependency versions in the local node_modules folder and our scripts will then use those.

**Comment by joequant** [comment]
The problem isn't in polymath but rather that polymath triggers a bug in the external ganache-cli server that causes a crash.  Running yarn won't fix the issue since the ethereum server is running external to polymath.

**Comment by maxsam4** [comment]
@joequant I really appreciate you playing around our repo!

ganache-cli is an npm package and running yarn will install the version of ganache-cli that has been tested with our repo. You can then run it from `./node_modules/.bin/ganache-cli`.

As you mentioned, the problem isn't in polymath and It's not something we can fix. Please try to understand that we can't add warnings about every nonworking version of every external dependency. 
Assume we have 10 dependencies and each dependency has 10 versions. That means there are 10^10 combinations of dependencies. Please understand that it's not humanly possible to test each and every combination.
 
We are supplying `yarn.lock` file with our repo that explicitly defines the versions of dependencies that we use and have tested. Please use those exact versions if you want a trouble-free experience.
