### ISSUE TITLE
removeModule could potentially bypass repleaceability

### ISSUE THREAD

**Issue by pabloruiz55** [PolymathNetwork/polymath-core#69]
Say we added 5 modules to the ST, the last one being not replaceable.
removeModule "deletes" a module by replacing it with the last one and then eliminating the last one.

So, if we were to remove module 3, now the last module is number 4, which is replaceable.

Don't know if it is a big deal though.

**Comment by adamdossa** [comment]
This is a good catch. I'll rework the replaceable logic a bit to fix this (just keep an overall replaceable flag per module type, rather than relying on the final module in the list to hold this value).

**Comment by adamdossa** [comment]
Fixed in #73
