### ISSUE TITLE
v3.0: add generateNewSecurityToken() to ISecurityTokenRegistry

### ISSUE THREAD

**Issue by ross-rosario** [PolymathNetwork/polymath-core#711]
**Note** This is in `dev-3.0.0` branch

Unlike `generateSecurityToken()`, the new `generateNewSecurityToken()` is not present in `ISecurityTokenRegistry` interface. That requires using two separate ABI while interacting with the smart contract, one for calls and the other for transactions.

Thanks

**Comment by ross-rosario** [comment]
On closer inspection, I realized that the issue is going to be fixed in #682, but we can keep this issue for tracking purposes. I'll close it as soon as the PR is merged.

**Comment by adamdossa** [comment]
PR is merged.
