### ISSUE TITLE
Denial of Service (DoS) Vulnerability

### ISSUE THREAD

**Issue by larrycameron80** [PolymathNetwork/polymath-core#813]
Denial of Service (DoS)
Vulnerable module: mem
Introduced through: solc@0.5.8
Detailed paths
Introduced through: polymath-core@PolymathNetwork/polymath-core#3a267ea44a549b7b31942daa6025b1d41189548d › solc@0.5.8 › yargs@11.1.0 › os-locale@2.1.0 › mem@1.1.0
Remediation: Upgrade to solc@0.5.11.
Overview
mem is an optimization used to speed up consecutive function calls by caching the result of calls with identical input.

Affected versions of this package are vulnerable to Denial of Service (DoS). Old results were deleted from the cache and could cause a memory leak.

**Comment by maxsam4** [comment]
@larrycameron80 Thanks for opening up an issue.

The vulnerability in question is not relevant to this repo. mem package is used to speed up compilation by solc and not as a public-facing cache in this repo.
