### ISSUE TITLE
Insecure Credential Storage Vulnerability

### ISSUE THREAD

**Issue by larrycameron80** [PolymathNetwork/polymath-core#814]
Insecure Credential Storage
Vulnerable module: web3
Introduced through: web3@1.2.1, solidity-coverage@0.6.7 and others
Detailed paths
Introduced through: polymath-core@PolymathNetwork/polymath-core#3a267ea44a549b7b31942daa6025b1d41189548d › web3@1.2.1
Introduced through: polymath-core@PolymathNetwork/polymath-core#3a267ea44a549b7b31942daa6025b1d41189548d › solidity-coverage@0.6.7 › web3@1.2.1
Introduced through: polymath-core@PolymathNetwork/polymath-core#3a267ea44a549b7b31942daa6025b1d41189548d › truffle-hdwallet-provider@1.0.17 › web3@1.2.1
Overview
web3 is a JavaScript API which connects to the Generic JSON RPC spec.

Affected versions of this package are vulnerable to Insecure Credential Storage. The current implementation of web3.js could result in wallet decryption under certain circumstances. When a wallet is saved and encrypted into local storage, a private key is needed to load the wallet. However, this private key is available via LocalStorage and is readable in plaintext on a webpage after a wallet is loaded.

This implementation could be abused by an attacker through client-side attacks such as Cross-site Scripting (XSS) and could result in theft of a user's wallet private key.

**Comment by maxsam4** [comment]
We don't use web3 as a Keystore and hence this vulnerability is not relevant to us. Thanks for raising a concern, though. We are always working on improving security.
